# Generated by Django 4.1.6 on 2023-02-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabless',
            fields=[
                ('name', models.CharField(default='name', max_length=500, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rows',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('Teilindikator', models.CharField(blank=True, max_length=500, null=True)),
                ('Datenquelle', models.CharField(blank=True, max_length=500, null=True)),
                ('Datum', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=500, null=True)),
                ('Wert', models.IntegerField(blank=True, null=True)),
                ('Top3', models.IntegerField(blank=True, null=True)),
                ('EUDurchschnitt', models.IntegerField(blank=True, null=True)),
                ('Tables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FTI_Monitor.tabless')),
            ],
        ),
    ]
