# Generated by Django 4.1 on 2023-03-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTI_Monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rows',
            name='Code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
