# Generated by Django 4.1 on 2023-03-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTI_Monitor', '0002_rows_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rows',
            name='Datum',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
