# Generated by Django 4.1 on 2023-03-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTI_Monitor', '0003_alter_rows_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rows',
            name='Status',
            field=models.CharField(default='Active', max_length=500),
        ),
    ]
