# Generated by Django 4.1 on 2023-03-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FTI_Monitor', '0004_alter_rows_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rows',
            name='Wert',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
